set(VCPKG_POLICY_EMPTY_PACKAGE enabled)

file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/bin)
execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink
    pkgconf${VCPKG_TARGET_EXECUTABLE_SUFFIX} pkg-config${VCPKG_TARGET_EXECUTABLE_SUFFIX}
    WORKING_DIRECTORY ${CURRENT_PACKAGES_DIR}/bin
)
