set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_BUILD_TYPE release)
set(VCPKG_ENV_PASSTHROUGH_UNTRACKED PATH Path)
set(VCPKG_LOAD_VCVARS_ENV ON)
cmake_path(SET VCPKG_CHAINLOAD_TOOLCHAIN_FILE
  NORMALIZE
  ${CMAKE_CURRENT_LIST_DIR}/../scripts/toolchains/x64-windows-minsizerel.cmake
)
