cmake_minimum_required(VERSION 3.30)

if(NOT _VCPKG_WINDOWS_TOOLCHAIN)
  set(_VCPKG_WINDOWS_TOOLCHAIN 1)
  set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL" CACHE STRING "")
  set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "")

  list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    VCPKG_CRT_LINKAGE VCPKG_TARGET_ARCHITECTURE VCPKG_SET_CHARSET_FLAG
    VCPKG_C_FLAGS VCPKG_CXX_FLAGS
    VCPKG_C_FLAGS_RELEASE VCPKG_CXX_FLAGS_RELEASE
    VCPKG_LINKER_FLAGS VCPKG_LINKER_FLAGS_RELEASE
    VCPKG_PLATFORM_TOOLSET
  )

  set(CMAKE_SYSTEM_NAME Windows CACHE STRING "")

  if(DEFINED VCPKG_CMAKE_SYSTEM_VERSION)
    set(CMAKE_SYSTEM_VERSION "${VCPKG_CMAKE_SYSTEM_VERSION}" CACHE STRING "" FORCE)
  endif()

  set(CMAKE_CROSSCOMPILING OFF CACHE STRING "")

  set(MP_BUILD_FLAG "")

  if(NOT(CMAKE_CXX_COMPILER MATCHES "clang-cl.exe"))
    set(MP_BUILD_FLAG "/MP ")
  endif()

  set(common_flags "/nologo /permissive- /DWIN32 /D_WINDOWS /utf-8 ${MP_BUILD_FLAG}")
  set(CMAKE_CXX_FLAGS " ${common_flags} /std:c++latest /GR /EHsc /Zc:__cplusplus /Zc:wchar_t ${VCPKG_CXX_FLAGS}" CACHE STRING "")
  set(CMAKE_C_FLAGS " ${common_flags} /std:clatest /Zc:__STDC__ ${VCPKG_C_FLAGS}" CACHE STRING "")

  set(CMAKE_RC_FLAGS "-c65001 /DWIN32" CACHE STRING "")

  set(CMAKE_CXX_FLAGS_MINSIZEREL " /MD /O1 /DNDEBUG /Zc:inline ${VCPKG_CXX_FLAGS_RELEASE}" CACHE STRING "")
  set(CMAKE_C_FLAGS_MINSIZEREL " /MD /O1 /Zc:inline ${VCPKG_C_FLAGS_RELEASE}" CACHE STRING "")
  set(CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_MINSIZEREL} CACHE STRING "")
  set(CMAKE_C_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE} CACHE STRING "")

  string(APPEND CMAKE_STATIC_LINKER_FLAGS_RELEASE_INIT " /nologo ")
  set(CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL "/nologo /DEBUG:NONE /INCREMENTAL:NO /OPT:REF /OPT:ICF ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")
  set(CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL "/nologo /DEBUG:NONE /INCREMENTAL:NO /OPT:REF /OPT:ICF ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")
  set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL "/nologo /DEBUG:NONE /INCREMENTAL:NO /OPT:REF /OPT:ICF ${VCPKG_LINKER_FLAGS} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")
  set(CMAKE_MODULE_LINKER_FLAGS_RELEASE ${CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL} CACHE STRING "")
  set(CMAKE_SHARED_LINKER_FLAGS_RELEASE ${CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL} CACHE STRING "")
  set(CMAKE_EXE_LINKER_FLAGS_RELEASE ${CMAKE_EXE_LINKER_FLAGS_MINSIZEREL} CACHE STRING "")

  unset(MP_BUILD_FLAG)
endif()
